COMMANDS = [
    # "config create",
    # "download hex",
    # "download tools",
    # "flash all",
    "flash bt121",
    "flash ex",
    "flash habs",
    "flash mn",
    "flash re",
    "flash xbee",
    # "show all",
    # "show configs",
    # "show devices",
    # "show rigids",
    # "show themes",
    # "show versions",
    # "upload hex",
    # "upload firmware",
    # "upload library",
]
